<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EPG [
  <!ELEMENT EPG (Configurations, EpgStates)>
  <!ATTLIST EPG version CDATA #IMPLIED>
  <!ELEMENT Configurations (StateTransisionTimeout,MenuTransisionTimeout, StateTransisionAnimationDuraiton, MenuTransisionAnimationDuraiton,RetryTimeout,RetriesCount)>
  <!ELEMENT StateTransisionTimeout EMPTY>
  <!ELEMENT MenuTransisionTimeout EMPTY>
  <!ELEMENT StateTransisionAnimationDuraiton EMPTY>
  <!ELEMENT MenuTransisionAnimationDuraiton EMPTY>
  <!ELEMENT RetryTimeout EMPTY>
  <!ELEMENT RetriesCount (#PCDATA)>
  <!ATTLIST StateTransisionTimeout time CDATA #REQUIRED>
  <!ATTLIST MenuTransisionTimeout time CDATA #REQUIRED>
  <!ATTLIST StateTransisionAnimationDuraiton time CDATA #REQUIRED>
  <!ATTLIST MenuTransisionAnimationDuraiton time CDATA #REQUIRED>
  <!ATTLIST RetryTimeout time CDATA #REQUIRED>
  <!ELEMENT EpgStates (State)*>
  <!ELEMENT State (ActivationCriterias,DirectDestinations?, Menu?, Menus?) >
  <!ATTLIST State name CDATA #REQUIRED>
  <!ATTLIST State extraAnimationDuration CDATA #IMPLIED>
  <!ATTLIST State xsi:type (DALSimpleMenuState|DALComplexMenuState) #IMPLIED>
  <!ELEMENT ActivationCriterias (ActivationCriteria)*>
  <!ELEMENT ActivationCriteria EMPTY>
  <!ATTLIST ActivationCriteria key CDATA #REQUIRED>
  <!ATTLIST ActivationCriteria value CDATA #REQUIRED>
  <!ELEMENT DirectDestinations (DirectDestination)*>
  <!ELEMENT DirectDestination (IrKey?, Delay?)>
  <!ATTLIST DirectDestination name CDATA #REQUIRED>
  <!ELEMENT IrKey EMPTY>
  <!ATTLIST IrKey name CDATA #IMPLIED>
  <!ATTLIST IrKey pressDuration CDATA #IMPLIED>
  <!ELEMENT Delay EMPTY>
  <!ATTLIST Delay time CDATA #IMPLIED>
  <!ELEMENT Menu (Items)>
  <!ELEMENT Items (Item)*>
  <!ELEMENT Item EMPTY>
  <!ATTLIST Item name CDATA #REQUIRED>
  <!ATTLIST Item dictionaryKey CDATA #IMPLIED>
  <!ATTLIST Item destination CDATA #IMPLIED>
  <!ELEMENT Menus ANY>

]>

<EPG xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="3.2">
  <Configurations>
    <StateTransisionTimeout time="30"/>
    <MenuTransisionTimeout time="10"/>
    <StateTransisionAnimationDuraiton time="2"/>
    <MenuTransisionAnimationDuraiton time="2"/>
    <RetryTimeout time="600"/>
    <RetriesCount>3</RetriesCount>
  </Configurations>
  <EpgStates>

    <!--Dummy state representing the 'out of sync' state-->
    <State name="UNKNOWN">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="unknownState"/>
      </ActivationCriterias>
      <DirectDestinations/>
    </State>

	
    <!-- LANGUAGE SELECTION, FIRST SCREEN  AFTER FORMAT-->
    <State xsi:type="DALSimpleMenuState" name="EPG LANGUAGE SELECTION">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="LanguageSelectionState"/>
        <ActivationCriteria key="scrnCtrl" value="LanguageSelectionScrnCtrl"/>
      </ActivationCriterias>

      <Menu layout="UpDown" type="NonCircular" selectionIdentifier="title">
        <Items>
		  <Item name="ENGLISH" dictionaryKey="" destination=""/>
		  <Item name="FRANÃ‡AIS" dictionaryKey="" destination=""/>
		  <Item name="NEDERLANDS" dictionaryKey="" destination=""/>
        </Items>
      </Menu>
    </State>
	
    <!--Live viewing-->
    <State name="LIVE">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="IdleState"/>
		<ActivationCriteria key="scrnCtrl" value="ScreenCntrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="CHANNEL BAR">
          <IrKey name="RETOUR"/>
        </DirectDestination>
        <DirectDestination name="ACTION BAR">
          <IrKey name="SELECT"/>
        </DirectDestination>
        <DirectDestination name="TRICKMODE BAR">
          <IrKey name="PAUSE"/>
        </DirectDestination>
	<DirectDestination name="CHANNEL LINEUP">
           <IrKey name="SELECT_UP" pressDuration="4"/>
        </DirectDestination>		
      </DirectDestinations>
    </State>

    <!--Playback viewing-->
    <State name="PLAYBACK">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="PlayBackIdleState"/>
        <ActivationCriteria key="scrnCtrl" value="ScreenCntrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="CHANNEL BAR">
          <IrKey name="RETOUR"/>
        </DirectDestination>
        <DirectDestination name="ACTION BAR">
          <IrKey name="SELECT"/>
        </DirectDestination>
        <DirectDestination name="TRICKMODE BAR">
          <IrKey name="PAUSE"/>
        </DirectDestination>
      </DirectDestinations>
    </State>

    <!--Channel Bar-->
    <State xsi:type="DALSimpleMenuState" name="CHANNEL BAR">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="ChBarState"/>
        <ActivationCriteria key="scrnCtrl" value="ChBarScreenCntrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
		<DirectDestination name="ACTION BAR">
          <IrKey name="SELECT"/>
        </DirectDestination>
		<DirectDestination name="CHANNEL LINEUP">
           <IrKey name="SELECT_UP" pressDuration="4"/>
        </DirectDestination>		
      </DirectDestinations>
      <Menu layout="RightLeft" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="NOW" dictionaryKey="DIC_NOW" destination="LIVE"/>
	  <Item name="NOW(LOCKED)" dictionaryKey="DIC_NOW" destination="INSERT PIN UNLOCK CHANNEL"/>
          <Item name="NEXT" dictionaryKey="DIC_NEXT" destination="ACTION BAR"/>
		  <Item name="ON DEMAND" dictionaryKey="DIC_CHANNEL_BAR_STORE" destination="STORE_LEAF_CATEGORY"/>
          <Item name="MORE LIKE THIS" dictionaryKey="DIC_SEARCH_REFINE_RESULT" destination="MORE LIKE THIS"/>
	  <Item name="UNLOCK" dictionaryKey="" destination="INSERT PIN UNLOCK CHANNEL"/>
        </Items>
      </Menu>
    </State>

    <!--Channel Lineup -->
    <State xsi:type="DALSimpleMenuState" name="CHANNEL LINEUP">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="FastChannelListState"/>
        <ActivationCriteria key="scrnCtrl" value="FastChannelScreenCntrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/> 
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
        </Items>
      </Menu>
    </State>

<!-- BOOKING CONFLICT-->
    <State name="BOOKIMG CONFLICT">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="PvrWarningOptionState"/>
        <ActivationCriteria key="scrnCtrl" value="ConflictOptionScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
		<DirectDestination name="CONFIRM RECORDING">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="AUTOMATICALLY" dictionaryKey="DIC_CONFLICT_ACTION_AUTOMATICALLY" destination="LIVE"/>
		  <Item name="CANCEL RECORDING" dictionaryKey="DIC_CONFLICT_ACTION_CANCEL" destination="LIVE"/>
          <Item name="MANUALLY" dictionaryKey="DIC_CONFLICT_ACTION_MANUALLY" destination="MAUNAL CANCEL OPTIONS"/>
        </Items>
      </Menu>	  
    </State>
	
 <!--	MAUNAL CANCEL OPTIONS -->
    <State  xsi:type="DALSimpleMenuState" name="MAUNAL CANCEL OPTIONS">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="PvrConflictListState" />
        <ActivationCriteria key="scrnCtrl" value="ConflictListScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
		<DirectDestination name="BOOKIMG CONFLICT">
          <IrKey name="RETOUR" />
        </DirectDestination>		
      </DirectDestinations>
	  <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
        </Items>
      </Menu>
    </State>
	
    <!--Zap Channel Bar (loads after 'back to live' from the player)-->
    <State xsi:type="DALSimpleMenuState" name="ZAP CHANNEL BAR">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="ZapTransState"/>
        <ActivationCriteria key="scrnCtrl" value="ChBarScreenCntrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="RightLeft" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="NOW" dictionaryKey="DIC_NOW" destination="LIVE"/>
          <Item name="UNLOCK" dictionaryKey="DIC_ACTION_UNLOCK" destination="INSERT PIN UNLOCK CHANNEL"/>		  
        </Items>
      </Menu>
    </State>

	<!-- INSERT_PIN_UNLOCK_CHANNEL -->
    <State xsi:type="DALSimpleMenuState" name="INSERT PIN UNLOCK CHANNEL">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="PincodeState"/>
        <ActivationCriteria key="scrnCtrl" value="PinScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="ZAP CHANNEL BAR">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="RightLeft" type="Circular" selectionIdentifier="title">
        <Items>
        </Items>
      </Menu>
    </State>

    <!--Action Bar -> Record Event, depends on weather the event is part of a series. if not, only the top 2 appear. if hes, the 3 lower items appear-->
    <State xsi:type="DALSimpleMenuState" name="CONFIRM RECORDING">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="EventRecordingState"/>
        <ActivationCriteria key="scrnCtrl" value="ActionsMenuScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="CONFIRM RECORDING" dictionaryKey="DIC_ACTION_LIST_RECORD_EVENT" destination="LIVE"/>
		  
		  <Item name="CONFIRM RECORDING FROM ALL CHANNELS" dictionaryKey="DIC_ACTION_LIST_RECORD_EVENT" destination="ALL CHANNELS"/>
          <Item name="RECORD THIS EPISODE" dictionaryKey="DIC_ACTION_LIST_RECORD_SERIE_EVENT" destination="LIVE"/>
          <Item name="RECORD ALL EPISODES" dictionaryKey="DIC_ACTION_LIST_RECORD_SERIE" destination="LIVE"/>
		  <Item name="CANCEL THIS EPISODE" dictionaryKey="DIC_DELETE_SCHED_RECORD" destination="LIVE"/>
		  <Item name="CANCEL ALL EPISODES" dictionaryKey="DIC_DELETE_BOOKING_ENTIRE_SERIES" destination="LIVE"/>		  		  
		  <Item name="CANCEL RECORDING" dictionaryKey="DIC_PROG_ACTION_CANCEL_RECORD" destination="LIVE"/>		  		  
		  <Item name="ADD EXTRA TIME" dictionaryKey="DIC_LIBRARY_MODIFY_PARAMS" destination="MODIFY PARAMETERS"/>
		  <Item name="MAKE FAVOURITE" dictionaryKey="DIC_PROG_ACTION_ADDTOFAVORITES" destination="LIVE"/>
		  <Item name="CONFIRM RECORDING" dictionaryKey="DIC_OK" destination="LIVE"/>
        </Items>
      </Menu>
    </State>	    
	
			<State xsi:type="DALSimpleMenuState" name="PERSONALIZED RECOMMENDATION ACTIVATION">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SettingsLeafState"/>
        <ActivationCriteria key="scrnCtrl" value="SETTINGSScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="SETTINGS">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="YES" DictionaryKey="" destination="MAIN MENU"/>
          <Item name="NO" dictionaryKey="" destination="MAIN MENU"/>
        </Items>
      </Menu>
    </State>
	
<!--MAIN MENU -> SEARCH -> KEYWORD -->
    <State name="KEYWORD_MODIFY">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="LibraryManualRecState"/>
        <ActivationCriteria key="scrnCtrl" value="END TIMEScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
		<DirectDestination name="MODIFY PARAMETERS 2">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
    </State> 
	
<!-- MODIFY PARAMETERS ->(son item ) ->MODIFY PARAMETERS2  -->
    <State xsi:type="DALSimpleMenuState" name="MODIFY PARAMETERS 2">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="LibraryManualRecState"/>
        <ActivationCriteria key="scrnCtrl" value="LibraryManualRecScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="CONFIRM RECORDING">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
	  <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
			<Item name="END TIME" dictionaryKey="DIC_END_TIME" destination="KEYWORD_MODIFY"/>
			<Item name="FREQUENCY" dictionaryKey="DIC_FREQUENCY_RECORD" destination="FREQUENCY"/>
			<Item name="CHANNEL" dictionaryKey="DIC_CHANNEL" destination="CHANNEL"/>	
			<Item name="DATE" dictionaryKey="DIC_DATE" destination="DATE"/>	
			<Item name="START TIME" dictionaryKey="DIC_START_TIME" destination="START TIME"/>
			<Item name="CONFIRM" dictionaryKey="DIC_CONFIRM" destination="LIVE"/>
        </Items>
      </Menu>            
    </State>
<!--ACTION BAR -> RECORD-> MODIFY PARAMETERS-->
    <State xsi:type="DALSimpleMenuState" name="MODIFY PARAMETERS">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="AuxAppState"/>
        <ActivationCriteria key="scrnCtrl" value="LibraryManualRecScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="CONFIRM RECORDING">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
	  <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
			<Item name="END TIME" dictionaryKey="DIC_END_TIME" destination="KEYWORD_MODIFY"/>
			<Item name="FREQUENCY" dictionaryKey="DIC_FREQUENCY_RECORD" destination="FREQUENCY"/>
			<Item name="CONFIRM" dictionaryKey="DIC_CONFIRM" destination="SCHEDULED RECORDINGS"/>
			<Item name="CHANNEL" dictionaryKey="DIC_CHANNEL" destination="CHANNEL"/>	
			<Item name="DATE" dictionaryKey="DIC_DATE" destination="DATE"/>	
			<Item name="START TIME" dictionaryKey="DIC_START_TIME" destination="START TIME"/>
        </Items>
      </Menu>            
    </State>
	<!--ACTION BAR -> RECORD-> MODIFY PARAMETERS-> START TIME  -->
    <State xsi:type="DALSimpleMenuState" name="START TIME">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="LibraryManualRecState"/>
        <ActivationCriteria key="scrnCtrl" value="START TIMEScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="MODIFY PARAMETERS 2">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
	  <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
			<Item name="0" dictionaryKey="" destination="START TIME"/>
			<Item name="1" dictionaryKey="" destination="START TIME"/>
			<Item name="2" dictionaryKey="" destination="START TIME"/>
			<Item name="3" dictionaryKey="" destination="START TIME"/>
			<Item name="4" dictionaryKey="" destination="START TIME"/>
			<Item name="5" dictionaryKey="" destination="START TIME"/>
			<Item name="6" dictionaryKey="" destination="START TIME"/>
			<Item name="7" dictionaryKey="" destination="START TIME"/>
			<Item name="8" dictionaryKey="" destination="START TIME"/>
			<Item name="9" dictionaryKey="" destination="START TIME"/>
			<Item name="CONFIRM" dictionaryKey="DIC_CONFIRM" destination="MODIFY PARAMETERS 2"/>
        </Items>
      </Menu>            
    </State>
	
		<!--Settings -> Define Auto Stand By Time -> NIGHT START TIME  -->
    <State xsi:type="DALSimpleMenuState" name="NIGHT START TIME">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SettingsLeafState"/>
        <ActivationCriteria key="scrnCtrl" value="START TIMEScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="DEFINE AUTO STANDBY TIME">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
	  <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
			<Item name="0" dictionaryKey="" destination="NIGHT START TIME"/>
			<Item name="1" dictionaryKey="" destination="NIGHT START TIME"/>
			<Item name="2" dictionaryKey="" destination="NIGHT START TIME"/>
			<Item name="3" dictionaryKey="" destination="NIGHT START TIME"/>
			<Item name="4" dictionaryKey="" destination="NIGHT START TIME"/>
			<Item name="5" dictionaryKey="" destination="NIGHT START TIME"/>
			<Item name="6" dictionaryKey="" destination="NIGHT START TIME"/>
			<Item name="7" dictionaryKey="" destination="NIGHT START TIME"/>
			<Item name="8" dictionaryKey="" destination="NIGHT START TIME"/>
			<Item name="9" dictionaryKey="" destination="NIGHT START TIME"/>
			<Item name="CONFIRM" dictionaryKey="DIC_CONFIRM" destination="DEFINE AUTO STANDBY TIME"/>
        </Items>
      </Menu>            
    </State>
	
		
		<!--Settings -> Define Auto Stand By Time -> NIGHT END TIME  -->
    <State xsi:type="DALSimpleMenuState" name="NIGHT END TIME">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SettingsLeafState"/>
        <ActivationCriteria key="scrnCtrl" value="END TIMEScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="DEFINE AUTO STANDBY TIME">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
	  <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
			<Item name="0" dictionaryKey="" destination="NIGHT END TIME"/>
			<Item name="1" dictionaryKey="" destination="NIGHT END TIME"/>
			<Item name="2" dictionaryKey="" destination="NIGHT END TIME"/>
			<Item name="3" dictionaryKey="" destination="NIGHT END TIME"/>
			<Item name="4" dictionaryKey="" destination="NIGHT END TIME"/>
			<Item name="5" dictionaryKey="" destination="NIGHT END TIME"/>
			<Item name="6" dictionaryKey="" destination="NIGHT END TIME"/>
			<Item name="7" dictionaryKey="" destination="NIGHT END TIME"/>
			<Item name="8" dictionaryKey="" destination="NIGHT END TIME"/>
			<Item name="9" dictionaryKey="" destination="NIGHT END TIME"/>
			<Item name="CONFIRM" dictionaryKey="DIC_CONFIRM" destination="DEFINE AUTO STANDBY TIME"/>
        </Items>
      </Menu>            
    </State>
	<!--ACTION BAR -> RECORD-> MODIFY PARAMETERS-> DATE  -->
    <State xsi:type="DALSimpleMenuState" name="DATE">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="LibraryManualRecState"/>
        <ActivationCriteria key="scrnCtrl" value="DATEScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="MODIFY PARAMETERS 2">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
	  <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
			<Item name="TODAY" dictionaryKey="DIC_DAY_TODAY" destination="MODIFY PARAMETERS 2"/>
        </Items>
      </Menu>            
    </State>
	<!--ACTION BAR -> RECORD-> MODIFY PARAMETERS-> CHANNEL  -->
    <State xsi:type="DALSimpleMenuState" name="CHANNEL">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="LibraryManualRecState"/>
        <ActivationCriteria key="scrnCtrl" value="CHANNELScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="MODIFY PARAMETERS 2">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
	  <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
			<Item name="Program_401" dictionaryKey="" destination="MODIFY PARAMETERS 2"/>
			<Item name="Program_402" dictionaryKey="" destination="MODIFY PARAMETERS 2"/>
			<Item name="Program_403" dictionaryKey="" destination="MODIFY PARAMETERS 2"/>
        </Items>
      </Menu>            
    </State>
	<!--ACTION BAR -> RECORD-> MODIFY PARAMETERS-> FREQUENCY-->
    <State xsi:type="DALSimpleMenuState" name="FREQUENCY">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="LibraryManualRecState"/>
        <ActivationCriteria key="scrnCtrl" value="FREQUENCYScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="MODIFY PARAMETERS 2">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="ONE TIME" dictionaryKey="DIC_ONE_TIME" destination="MODIFY PARAMETERS 2"/>
		  <Item name="DAILY" dictionaryKey="DIC_DAILY" destination="MODIFY PARAMETERS 2"/>
		  <Item name="WEEKLY" dictionaryKey="DIC_WEEKLY" destination="MODIFY PARAMETERS 2"/>		  
		  <Item name="WEEKDAY" dictionaryKey="DIC_WEEKDAY" destination="MODIFY PARAMETERS 2"/>
		  <Item name="WEEKEND" dictionaryKey="DIC_WEEKEND" destination="MODIFY PARAMETERS 2"/>		  
        </Items>
      </Menu>
    </State>

    <!--Action Bar-->
    <State xsi:type="DALSimpleMenuState" name="ACTION BAR">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="ProgramActionState"/>
        <ActivationCriteria key="scrnCtrl" value="ActionsMenuScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
		</DirectDestination>
        <DirectDestination name="LIVE">
          <IrKey name="RETOUR"/>		  
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="SEARCH" dictionaryKey="DIC_PROG_ACTION_SEARCH" destination="SEARCH"/>
          <Item name="A//V SETTINGS" dictionaryKey="DIC_PROG_ACTION_FORMAT" destination="A//V SETTINGS"/>
          <Item name="MORE LIKE THIS" dictionaryKey="DIC_STORE_RELATED" destination="MORE LIKE THIS"/>
          <Item name="INFO" dictionaryKey="DIC_PROG_ACTION_SUMMARY" destination="INFO"/>
          <Item name="PAUSE" dictionaryKey="DIC_PROG_ACTION_PAUSE" destination="TRICKMODE BAR"/>
          <Item name="PLAY FROM LAST VIEWED" dictionaryKey="DIC_PROG_ACTION_PLAYFROMLASTVIEWEDPOS" destination="TRICKMODE BAR"/>	
		  <Item name="PROTECT" dictionaryKey="DIC_PROG_ACTION_PROTECT" destination=""/>
		  <Item name="UNPROTECT" dictionaryKey="DIC_PROG_ACTION_UNPROTECT" destination=""/>
		  <Item name="ADD EXTRA TIME" dictionaryKey="DIC_LIBRARY_MODIFY_PARAMS" destination="MODIFY PARAMETERS"/>
          <!--Item name="PLAY FROM BEGINNING" dictionaryKey="DIC_PROG_ACTION_PLAYFROMBEGINNING" destination="TRICKMODE BAR"/-->		 
		  <Item name="PLAY FROM BEGINNING" dictionaryKey="DIC_PROG_ACTION_PLAYFROMBEGINNING" destination=""/>	
		  <Item name="LOCK EVENT" dictionaryKey="DIC_ACTION_LOCK" destination="LIVE"/>	
		  <Item name="UNLOCK EVENT" dictionaryKey="DIC_ACTION_UNLOCK" destination="LIVE"/>	
          <Item name="VIEW" dictionaryKey="DIC_PROG_ACTION_VIEW" destination="LIVE"/>
          <Item name="RECORD" dictionaryKey="DIC_PROG_ACTION_RECORD" destination="CONFIRM RECORDING"/>
          <Item name="CANCEL RECORDING" dictionaryKey="DIC_PROG_ACTION_CANCEL_RECORD" destination="CONFIRM RECORDING"/>
          <Item name="DELETE" dictionaryKey="DIC_DELETE_SCHED_RECORD" destination="CONFIRM DELETE"/>
          <Item name="DELETE ALL" dictionaryKey="DIC_DELETE_ALL_BOOKINGS" destination="CONFIRM DELETE"/>
	      <Item name="STOP RECORDING" dictionaryKey="DIC_PROG_ACTION_STOP_RECORD" destination="CONFIRM DELETE"/>		  
          <Item name="PLAY" dictionaryKey="DIC_PROG_ACTION_PLAY" destination="TRICKMODE BAR"/>
          <Item name="ADD REMINDER" dictionaryKey="DIC_PROG_ACTION_REMINDER" destination="CONFIRMATION"/>
		  <Item name="CANCEL REMINDER" dictionaryKey="DIC_PROG_ACTION_CANCEL_REMINDER" destination="CONFIRMATION"/>
         <Item name="MAKE FAVOURITE" dictionaryKey="DIC_PROG_ACTION_ADDTOFAVORITES" destination="LIVE"/>
		  <Item name="REMOVE FROM FAVOURITES" dictionaryKey="DIC_CH_ACTION_REMOVE_FAVORITE" destination="LIVE"/>
		  <Item name="TELETEXT" dictionaryKey="DIC_ACTION_TELETEXT" destination="TELETEXT"/>
          <Item name="BACK TO LIVE TV" dictionaryKey="DIC_PROG_ACTION_BACK_TO_LIVE" destination=""/> 
          <Item name="LAST CHANNEL" dictionaryKey="DIC_PROG_ACTION_LAST_VIEWED" destination="LIVE"/>
		  <Item name="LOCK CHANNEL" dictionaryKey="DIC_PROG_ACTION_LAST_VIEWED" destination="LIVE"/>		  
		  <Item name="STOP" dictionaryKey="DIC_PROG_ACTION_STOP" destination="TRICKMODE BAR"/>
		  <Item name="FAVOURITE CHANNELS" dictionaryKey="DIC_SETTINGS_FAVOURITES" destination="CONFIRM RECORDING"/>
		  <Item name="START TIME" dictionaryKey="DIC_START_TIME" destination="START TIME"/>
		  <Item name="WATCH TRAILER" DictionaryKey="DIC_STORE_WATCH_TRAILER" destination=""/>
		  <Item name="CANCEL THIS EPISODE" dictionaryKey="DIC_DELETE_SCHED_RECORD" destination="CONFIRM DELETE"/>
		  <Item name="CANCEL ALL EPISODES" dictionaryKey="DIC_DELETE_BOOKING_ENTIRE_SERIES" destination="CONFIRM DELETE"/>
          <Item name="ENABLE FAVOURITE MODE" dictionaryKey="DIC_ENABLE_FAVOURITE_MODE" destination="LIVE"/>	
          <Item name="DISABLE FAVOURITE MODE" dictionaryKey="DIC_DISABLE_FAVOURITE_MODE" destination="LIVE"/>
          		  
        </Items>
      </Menu>
    </State>
	
     
    <!--ACTION BAR  SEARCH-->
    <State xsi:type="DALSimpleMenuState" name="SEARCH">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SearchHomeScreenState"/>
        <ActivationCriteria key="scrnCtrl" value="ActionsMenuScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="ACTION BAR">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
	  <Menu layout="UpDown" type="NonCircular" selectionIdentifier="title">
        <Items>
          <Item name="KEYWORD" dictionaryKey="DIC_MAIN_MENU_KEYWORD" destination="KEYWORD"/>        
		  <Item name="MORE OPTIONS" dictionaryKey="DIC_MAIN_MENU_ADVANCED" destination="MORE OPTIONS"/>        
        </Items>
      </Menu>	  
	 </State>


	
    <!--ACTION BAR -> A/V SETTINGS-->
    <State xsi:type="DALSimpleMenuState" name="A//V SETTINGS">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="FormatSelectionState"/>
        <ActivationCriteria key="scrnCtrl" value="ActionsMenuScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="ACTION BAR">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="NonCircular" selectionIdentifier="title">
        <Items>
          <Item name="SUBTITLES" dictionaryKey="DIC_PROG_ACTION_SUBTITLE" destination="SUBTITLES"/>        
		  <Item name="AUDIO" dictionaryKey="DIC_PROG_ACTION_AUDIO_LIST" destination="AUDIO"/>        
		  <Item name="VIDEO" dictionaryKey="DIC_PROG_ACTION_VIDEO" destination="VIDEO SELECTION"/>        
        </Items>
      </Menu>
    </State>

	<!--ACTION BAR - A/V SETTINGS -> VIDEO SELECTION-->
    <State xsi:type="DALSimpleMenuState" name="VIDEO SELECTION">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="VideoSelectionState"/>
        <ActivationCriteria key="scrnCtrl" value="ActionsMenuScrnCtrlr"/>
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="A//V SETTINGS">
          <IrKey name="RETOUR"/>
        </DirectDestination>
      </DirectDestinations>